# Generated by Django 5.1.2 on 2024-11-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wt_scrooge_capital", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transactions",
            new_name="Transaction",
        ),
    ]
