# Generated by Django 5.1.2 on 2024-11-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wt_scrooge_capital", "0002_rename_transactions_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-purchase_date"]},
        ),
    ]
