# Generated by Django 5.1.2 on 2024-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wt_scrooge_capital", "0003_alter_transaction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="default123", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="default123", max_length=50, unique=True),
        ),
    ]
