# Generated by Django 5.1.2 on 2024-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wt_scrooge_capital", "0005_remove_userprofile_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpricehistory",
            name="price_history",
            field=models.TextField(default=""),
        ),
    ]
